<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>AvaloniaPdfViewer</RootNamespace>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Description>Avalonia PDF Viewer in an Avalonia UI control for viewing PDF files.</Description>
        <Authors>Chris Gonzales</Authors>
        <Version>1.0.0</Version>
        <PackageTags>Avalonia UI Control pdf</PackageTags>
        <Copyright>Copyright 2024 Chris Gonzales</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIconUrl>https://raw.githubusercontent.com/chrisg32/AvaloniaPdfViewer/main/icon.png</PackageIconUrl>
        <PackageIcon>icon.png</PackageIcon>
        <PackageProjectUrl>https://github.com/chrisg32/AvaloniaPdfViewer</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>AvaloniaPdfViewer</PackageId>
        <Company>Chris Gonzales</Company>
        <Product>Avalonia PDF Viewer</Product>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/chrisg32/AvaloniaPdfViewer</RepositoryUrl>
        <AssemblyName>AvaloniaPdfViewer</AssemblyName>
        <NeutralLanguage>en-US</NeutralLanguage>
        <PackageVersion>1.0.0</PackageVersion>
        <Title>Avalonia PDF Viewer</Title>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../icon.png" Pack="true" PackagePath="" />
        <None Include="../README.md" Pack="true" PackagePath="" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Avalonia" Version="12.1.1" />
      <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
      <PackageReference Include="ReactiveUI" Version="20.1.1" />
      <PackageReference Include="DynamicData" Version="9.4.33" />
      <PackageReference Include="PDFtoImage" Version="5.4.0" />
      <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
      <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="4.151.1" />
      <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="4.151.1" />
      <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
    </ItemGroup>

</Project>
